### ISSUE TITLE
Console Error in Back-office: "No url found for api name gMapsBaseUrl"

### ISSUE THREAD

**Issue by hfloyd** [ArnoldV/Our.Umbraco.GMaps#101]
Umbraco version 8.18.3 | Our.Umbraco.GMaps version 2.0.5

Hi, when I added a DataType using the GMaps property editor to a Doctype and go to the Content node to edit it, I see this:
![image](https://user-images.githubusercontent.com/1252593/167024196-fac4c05b-3e51-4f65-a8db-43ad279d8384.png)

And there is a JS Console Error:
![image](https://user-images.githubusercontent.com/1252593/167024487-714eebd4-2991-49f2-9fc1-a557611e2394.png)

I have tried adding the API key to the DataType and also to the web.config. I have "hard-refreshed" the browser, but all with the same result. Has anyone seen this issue before?

**Comment by robertjf** [comment]
hm.  This would indicate the dll isn't installed properly maybe?  I don't think it's related to the API key.  Will need to investigate.

**Comment by hfloyd** [comment]
Thanks for your reply. 🙂 I installed via nuget, but as per the other logged issue, the app_plugins folder was not  copied over, so I pulled the source code and copied it from there... I thought the DLLs had been installed, but I can double-check when I'm back at my computer.

**Comment by robertjf** [comment]
brilliant :)  I'm working on issue #99 at the moment and should have a build out for you to play with soonish

**Comment by robertjf** [comment]
@hfloyd I've just pushed release 2.0.6 which should resolve the issue with getting the App_Data directory in place - if you are able, can you test and let me know if this is still an issue (release should be out soon on NuGet)
