### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by levipadre** [ArnoldV/Our.Umbraco.GMaps#11]
Hi,

Could you provide an example? I have this code, but I only receive `Our.Umbraco.GMaps.Models.GmapsModel` result for `@gmap`

My code so far:
```
@inherits Umbraco.Web.Mvc.UmbracoViewPage

@{
   var locations = Model.Root().Children.Where(x => x.IsDocumentType("homepage")).FirstOrDefault();

    foreach (var location in locations)
    {
        var gmap = location.Value("location");
        <div>@gmap</div>
    }
}
```

**Comment by dpedrovich** [comment]
> Hi,
> 
> Could you provide an example? I have this code, but I only receive `Our.Umbraco.GMaps.Models.GmapsModel` result for `@gmap`
> 
> My code so far:
> 
> ```
> @inherits Umbraco.Web.Mvc.UmbracoViewPage
> 
> @{
>    var locations = Model.Root().Children.Where(x => x.IsDocumentType("homepage")).FirstOrDefault();
> 
>     foreach (var location in locations)
>     {
>         var gmap = location.Value("location");
>         <div>@gmap</div>
>     }
> }
> ```

The GmapsModel consist of:

- GmapsAddress Address
  - string Coordinates
  - string FullAddress
  - string PostalCode
  - string City
  - string State
  - string Country

- GmapsMapConfig MapConfig
  - string Country
  - string ApiKey
  - string Zoom
  - string CenterCoordinates
  - string Style
  - string MapType


So you should be able to get for example Coordinates with "@gmap.Address.Coordinates".

**Comment by levipadre** [comment]
Thanks for the response. I tried you suggested, but got an error: `CS1061: 'object' does not contain a definition for 'Address' and no accessible extension method 'Address' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?`

Here is my whole code. If you see what's the problem, please let me know.

```
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@using Our.Umbraco.GMaps.Extensions

@{
    var developments = Model.Root().Children.Where(x => x.IsDocumentType("developments")).FirstOrDefault();
}


@{
    foreach (var development in developments.Children.Where(x => x.IsVisible()))
    {
        var gmap = development.Value("location");
        <div>@gmap.Address.Coordinates</div>
    }
}
```
