### ISSUE TITLE
Zoom int or string

### ISSUE THREAD

**Issue by jonas-jaderberg** [ArnoldV/Our.Umbraco.GMaps#111]
Hi,
I create locations via code and use the models, when I serialize I have problem with the Zoom property. In the model it's defined as a string

[DataMember(Name = "zoom")]
        [JsonProperty("zoom")]
        public string Zoom { get; set; }

But, that will not work with the map control. I have found out that it has to be a int to work with the map control.

**Comment by robertjf** [comment]
@jonas-jaderberg the Zoom property being a string is a legacy issue - I'm not sure why it's causing problems when you serialise though?  can you demonstrate with a code sample perhaps?

**Comment by jonas-jaderberg** [comment]
@robertjf  here is some sample code which I use when I import data that I have geocoded. It also include that hack I do to fix the problem.
```
      Our.Umbraco.GMaps.Models.Map gmap = new Map();
      gmap.Address = new Address();
      gmap.Address.Coordinates = new Location();
      gmap.Address.Coordinates.Latitude = r.Results[0].Geometry.Location.Lat;
      gmap.Address.Coordinates.Longitude = r.Results[0].Geometry.Location.Lng;

      gmap.MapConfig = new MapConfig();
      gmap.MapConfig.Zoom = "15";

      string json = JsonConvert.SerializeObject(gmap);
   
      //Hack to get zoom to an int. Probably bug that's a string in model.
      //If a string the map won't show up and there is an error saying that zoom is not an int.
      json = json.Replace("\"zoom\":\"15\"", "\"zoom\":15");

      d.SetValue("Position", json);
```
The problem is the in the model it's a string but in the json it has to be a int.

**Comment by robertjf** [comment]
@jonas-jaderberg can you explain where the error shows up?  Do you get it when trying to set the value, read it out, or when rendering the map in the Umbraco BackOffice?   Is it a JavaScript error or C#?

**Comment by robertjf** [comment]
@jonas-jaderberg I've relented and made Zoom an int 😅 - version bumped to 2.1.0 as this is a potential breaking change.  I've also fixed the controller so it can automatically convert from string to number in legacy data.

**Comment by jonas-jaderberg** [comment]
Tested 2.1.0 and it worked, great!

**Comment by Ambertvu** [comment]
@robertjf could you also set a default zoom level when using legacy data?

I have to look into it a bit deeper what the exact problem is, but since the upgrade it breaks for me (legacy v8 upgraded to v11) with the error:

JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'mapconfig.zoom', line 1, position 224.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
