### ISSUE TITLE
Umbraco 10 support

### ISSUE THREAD

**Issue by Aubit** [ArnoldV/Our.Umbraco.GMaps#114]
Hi, 

This is more of a question than an issue. Is there a plan for adding Umbraco 10 support to the package, and if so when is that being considered?

Cheers.

**Comment by robertjf** [comment]
@Aubit I've just tested the solution, and it's already compatible with Umbraco 10 without modification.  If you come across any issues when installing it on an Umbraco 10 installation, please re-open this ticket with some specific details and I'll take a look.
