### ISSUE TITLE
files are copying into every project inside the solution

### ISSUE THREAD

**Issue by Navorski** [ArnoldV/Our.Umbraco.GMaps#119]
If you have a solution with multiple projects, and the only project where you want the GMaps to be in is the site project itself. But when you build the project,, every project inside the solution is getting /App_Plugins/Our.Umbraco/GMaps folder with their css, js, views, lang inside.
This is probably not the correct way

**Comment by Navorski** [comment]
It actually happens when a project contains EntityFramework, (maybe others too) then it gets copied to that project.

**Comment by robertjf** [comment]
@Navorski I need to know more about the setup of your projects - are you including the `Our.Umbraco.GMaps` or the `Our.Umbraco.GMaps.Core` nuGet package?  The Core package includes the dlls only, the non-Core package includes the ~/App_Plugins files...

**Comment by Navorski** [comment]
@robertjf I've done some tests, and it is quite simple to reproduce.

- Visual Studio 2022
- Umbraco v10.1.0
- GMaps v2.1.0

I am creating an Umbraco solution with the SITE project inside.
I then add a second project to the solution.
In dependencies, i make sure the second project is depending on the .SITE project
When you build the application (Build Solution / Ctrl + Shift + B) the App_Plugins folder is occuring in the library project, while i don't need any files for the GMaps in there.

test.sln
-> test.SITE.csproj
-> test.TEST.csproj

test.SITE has the our.umbraco.Gmaps installed, 
test.TEST has no packages installed at all, only just a dependency to the SITE project.

**Comment by robertjf** [comment]
hey @Navorski,

I assume the .TEST project is your library project?  Is there a reason that it depends on the .SITE project and not the other way around?

**Comment by Navorski** [comment]
@robertjf 
I understand, but this is just a testcase to find out when this issue was occuring, in my real life application its a different setup
just for FYI this is how it actually is

project.SITE (depending on all projects) => actual site project **with Gmaps installed**
project.MODELS => Generated models + all other data models **with Gmaps installed** for the models builder
project.DATABASE (depending on the MODELS project) => mappings + stores for a custom database
... more projects all depending on the MODELS project

so all projects that are depending on the models project have the issue with Gmaps copied into their project

**Comment by robertjf** [comment]
@Navorski as I mentioned above, you should be using the `Our.Umbraco.GMaps.Core` nuget package for your non-Umbraco site projects, not `Our.Umbraco.GMaps`.  This will resolve your issue.
