### ISSUE TITLE
Coordinates are not parsed correctly on non-en-US cultures

### ISSUE THREAD

**Issue by arknu** [ArnoldV/Our.Umbraco.GMaps#123]
The parsing of coordinates don't specify the InvariantCulture, which means that on non-en-US cultures, the value "55.10694050000001" gets parsed as "5510694050000001", which obviously messes up the coordinates rather badly. 

I suspect the problem is this line:
https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/aa98772acb24a5ca24b355bb434bb3e480bfe878/Our.Umbraco.GMaps.Core/Models/Location.cs#L39

I'm working on a PR to address this issue.

**Comment by arknu** [comment]
PR is here: https://github.com/ArnoldV/Our.Umbraco.GMaps/pull/124

And thank you for a very useful package

**Comment by robertjf** [comment]
Thanks @arknu  :)
