### ISSUE TITLE
Core dll not included for .NET 6 in NuGet package

### ISSUE THREAD

**Issue by rasmusjp** [ArnoldV/Our.Umbraco.GMaps#125]
When installing the package on Umbraco 10 the `Our.Umbraco.GMaps.Core.dll` does not get published, it looks like it's because the NuGet package is not targeting .NET 6, I noticed that the README also mentiones Umbraco 11 but I'd suspect this also doesn't work since that runs on .NET 7

**Comment by ArnoldV** [comment]
We are doing Umbarco 11 this week and did not do the release yet.
Can you do a PR then I'll merge it in.
