### ISSUE TITLE
not loading in backoffice

### ISSUE THREAD

**Issue by benehudson** [ArnoldV/Our.Umbraco.GMaps#135]
Umbraco v 8.17

Gmaps v 2.1.3

Gmaps works as expected on my local machine. But, fails in the back office once I publish it to my server.

Some screenshots here:  https://our.umbraco.com/forum/using-umbraco-and-getting-started//110905-ourumbracogmaps-not-loading-in-backoffice

Here's the error message in Chrome Dev Console:  Error: [$injector:unpr] Unknown provider: GMapsMapsFactoryProvider <- GMapsMapsFactory <- GMapsMapsController

**Comment by benehudson** [comment]
Figured out I had to update my clientdependency.config file. please close this ticket

**Comment by dotcom9** [comment]
ClientDependency.config does not existing Umbraco 11.2.2 but the reported problem still exists. What is the solution for this issue in later releases?

**Comment by robertjf** [comment]
@dotcom9 can you please open a new ticket if you're still having problems with this, and provide as much detail as you can -  gMaps version, Umbraco version, and any error messages you're receiving.

Ta
