### ISSUE TITLE
Controller registered as a front-end controller and not a backoffice controller

### ISSUE THREAD

**Issue by devantler** [ArnoldV/Our.Umbraco.GMaps#136]
Currently, the `GoogleMapsController` is implemented as a `UmbracoApiController`. These controllers are meant for front-end controllers and not back-office controllers. This creates an issue if you want to use the package without registering the website to the DI container, as the controller is no longer added automatically.

Would it be possible for you to implement the controller as an `UmbracoAuthorizedJsonController`? This will ensure the controller is registered when calling

```csharp
services.AddUmbraco(_env, _config).AddBackOffice()
```

And not:

```csharp
services.AddUmbraco(_env, _config).AddWebsite()
```

**Comment by robertjf** [comment]
Pre-release for 2.1.4 is going out for this - feel free to test :)
