### ISSUE TITLE
Zoom currently breaks when using Legacy data (str vs int)

### ISSUE THREAD

**Issue by Ambertvu** [ArnoldV/Our.Umbraco.GMaps#138]
So I fixed it :-)
https://github.com/ArnoldV/Our.Umbraco.GMaps/pull/137

**Comment by robertjf** [comment]
Great work @Ambertvu  - will get it out in a release soon

**Comment by robertjf** [comment]
Pre release for 2.1.4 is going out including this fix - feel free to test :)

**Comment by Ambertvu** [comment]
@robertjf Works like a charm, whooo! :-D
