### ISSUE TITLE
Prevent address values from being format to all lowercase in views ?

### ISSUE THREAD

**Issue by frederiquefortier** [ArnoldV/Our.Umbraco.GMaps#149]
Hi, I really like this plugin, but I have one small issue I didn't managed to fix : 

When selecting a address from the autocomplete feature, it show up as expected in the backoffice, but once I'm in my view, the initial formatting is lost and everything is in lowercase. At the beginning, I thought it was because of how the information is keep in memory, but if I changed the gmaps property type to a rich text editor, I can see that the data in memory has the uppercases and lowercase at the accurate location in the string. 

Example in backoffice rich text editor: 
![image](https://github.com/ArnoldV/Our.Umbraco.GMaps/assets/48362702/cbd47e99-d78b-4837-8d20-af139c731f2d)

Example once print in my view :
![image](https://github.com/ArnoldV/Our.Umbraco.GMaps/assets/48362702/fe21c575-5d78-43cb-87b8-c5ac99194dc1)

I can't simply capitalize myself since in some address, I'll have a string like this : "54 Côte **d**u Palais", where I want one word to stay in lowercase. At the moment, my solution is to add another property where my users can enter the full street address in the formatting they want, but since I know the info is already there with the plugin, I would prefer to use it. 

Would it be possible to fixed this please? 

Thanks you!

**Comment by robertjf** [comment]
Hi @frederiquefortier  it's very unlikely to be an issue with the data stored - as you say, it's already capitalised.  It's more likely to be the formatting you're applying at the front end with CSS or similar...

**Comment by robertjf** [comment]
Hm.  That's very odd - there's nothing in the code to actually transform it all to lowercase...

**Comment by frederiquefortier** [comment]
I'm quite confuse myself. 

I realized I forgot to mention my Umbraco version, it's version 10.7.0. I don't know if it can be link (I'm frankly not that great at backend), but my website is also bilingual.

**Comment by robertjf** [comment]
What version of the plugin do you have installed?  Not that it should matter, there's nothing there to transform as I said...

**Comment by robertjf** [comment]
can you share the code you are using to retrieve the property value?

**Comment by Jonty-Schmidt** [comment]
@robertjf I believe this issue is caused by line 36 of the SingleMapPropertyValueConverter, which lowercases the JSON before it is deserialised, in order to perform `.Replace` and `.Contains` first:
```
  // Handle pre v2.0.0 data.
inter = inter.ToString().ToLower().Replace("google.maps.maptypeid.", string.Empty);
bool legacyData = inter.ToString().Contains("latlng");
```

I have found that if the ToLower() on line 36 is removed, this issue is resolved. In order to maintain the functionality of the `.Replace` and `.Contains` usages, may I suggest:
- Removing the use of `.Replace("google.maps.maptypeid.", string.Empty`, as the models this JSON is deserialised to lack this property, so it will be discarded on deserialisation anyway
- Running `ToLower()` on the `legacyData` check itself, without modifying the value of `inter`, eg `bool legacyData = inter.ToString().ToLower().Contains("latlng")`

**Comment by warrenbuckley** [comment]
@ArnoldV @robertjf 

I can confirm this is an issue with the Property Value Convertor code as mentioned by @Jonty-Schmidt and this had my head scratching for a while to figure out why it was coming out lowercase, when Examine and the DB stores the address in the correct casing.

Here is the Umbraco HQ address that renders out in lowercase when rendered out on the frontend

![image](https://github.com/ArnoldV/Our.Umbraco.GMaps/assets/1389894/135883bc-ec72-40dc-b84e-30374a4fba43)

And here it is in Examine storing the JSON value correctly without the address being lowercased

![image](https://github.com/ArnoldV/Our.Umbraco.GMaps/assets/1389894/0d40840a-ee43-4adb-aad9-d33963e997a0)


I will submit a PR shortly to fix this and will probably take @Jonty-Schmidt suggestion as the fix.
