### ISSUE TITLE
NuGet package for version 1.3.0 doesn't include package.manifest

### ISSUE THREAD

**Issue by AliSheikhTaheri** [ArnoldV/Our.Umbraco.GMaps#17]
Hi Arnold,

I have installed this package on Umbraco 8.2 but the property editor doesn't appear. I have cleaned and rebuilt a few times. is this package compatible with 8.2? 

Thanks
Ali

**Comment by ArnoldV** [comment]
Hey Ali!

The property does not render on the page or does not show in the data types?
make sure the package.manifest file is in the Our.Umbraco.GMaps folder in /app_plugins.

**Comment by AliSheikhTaheri** [comment]
Hi Arnold,

It does not show in the list of data types when I try to create a new data type.

Interestingly, I realised when I install it through Nuget it installs version 1.3.0, which the data type doesn't show up and there is no package.manifest file. However, when I installed the package via Umbraco the version 1.2.0 was installed and the package.manifest file is in version 1.2.0 and the data type works perfectly. 

Having said above, it means that the version 1.3.0 installed by Nuget is missing the package.manifest file. 

I also have a question which has nothing to do with this as I managed to make it work with version 1.2.0. 

Which model in the below code I should be using to get the value from database and which model should I use to write it back to the database via ContentService.SetValue("propertyAlais", SomethingModel)

`CurrentPage.Value<SomethingModel>` 

Thanks for your help 
Cheers

Ali

**Comment by ronaldbarendse** [comment]
Yes, looks like version 1.3 indeed doens't include the package.manifest in the NuGet version!

**Comment by ronaldbarendse** [comment]
Looks like this file was not changed from `none` to `content`: https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/a24d05b4cf725f2dd7dbba426e82f5dbb870b3fd/src/Our.Umbraco.GMaps.Core/Our.Umbraco.GMaps.Core.csproj#L245

**Comment by ronaldbarendse** [comment]
Fixed in version 1.3.1: https://www.nuget.org/packages/Our.Umbraco.GMaps/1.3.1 🎉 Thanks for reporting @AliSheikhTaheri!

FYI You only need to install the NuGet version, as the Umbraco Package isn't updated with the latest versions.
