### ISSUE TITLE
Only 1 map allowed on a page

### ISSUE THREAD

**Issue by shearer3000** [ArnoldV/Our.Umbraco.GMaps#21]
hello
due to hardwired code in MapScripts:
`var map = new google.maps.Map(document.getElementById('map')`
only 1 map can be output on a page.

Is it possible to pass in the element id for the map? (e.g. via model).  That would mean mutiple maps could be rendered on a page if desired.

thanks
Andrew

**Comment by ronaldbarendse** [comment]
Yes, `@Html.RenderMapScripts(...)` requires an element with id `map`, as that's indeed used in `MapScripts.cshtml`.

Version 2 removes the helper method and partial view, because it isn't flexible and you're better off manually adding the scripts to your front-end views.
