### ISSUE TITLE
Places Autocomplete popup is hidden due to low z-index

### ISSUE THREAD

**Issue by arknu** [ArnoldV/Our.Umbraco.GMaps#22]
It seems the z-index of the overlays in Umbraco have been changed to be higher that 1000. Since that is the z-index of the places popup, it is hidden and unusable. I believe this issue only occurs when the property editor is used in an infinite edit popup, like the new Block List Editor in 8.7.

Simply increasing the z-index to 10000 allows it to work.

PR coming up shortly.

**Comment by ronaldbarendse** [comment]
Thanks for reporting this issue @arknu!

Looking at how the Google Maps Place Autocomplete widget works, it adds the `.pac-container` element at the end of the document (just before the body closing tag), so it's not within the current z-index stacking context of the editor: https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete.

Increasing the z-index of this container (defaults to 1000) will indeed solve it (for now) 👍
