### ISSUE TITLE
Error when saving and publishing map

### ISSUE THREAD

**Issue by craigs100** [ArnoldV/Our.Umbraco.GMaps#29]
Saving and publishing a map causes "Duplicate alias" server error  (umb 8.9.0):-
![image](https://user-images.githubusercontent.com/1143883/98045308-36ac9980-1e20-11eb-99a3-7e8adce89597.png)

**Comment by ronaldbarendse** [comment]
@craigs100 How is this related to this package/property editor? Looking at the partial stack trace, it's a database error when trying to remove a document version 😕

**Comment by craigs100** [comment]
@ronaldbarendse It only happens when the map dataType is added to the page's docType. Therefore I don't think it was unreasonable to assume the dataType was the cause. If I remove the map dataType all is well, but I have no map :(
P.S. I'm genuinely impressed with your stacktrace reading ability.

**Comment by ronaldbarendse** [comment]
Well, the line number (297) and method name (`DeleteVersion`) for the `DocumentRepository` seem to reference the following code: https://github.com/umbraco/Umbraco-CMS/blob/0140d906a5a66d3ba512332e845a64d36169f911/src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs#L289-L297

As the column `Id` is used in both the INNER JOIN and WHERE part of the query performed by Umbraco, I would assume this isn't supported by SQLCE. I would advise creating an issue for this and/or switching from SQLCE to SQL Server Express/LocalDB: https://www.zpqrtbnk.net/posts/a-database-for-umbraco/.

**Comment by craigs100** [comment]
Thanks for that. If it is a SQLCE issue then it might be an idea to add a note to the package description: not suitable for use with SQLCE.

It's just a very simple, low traffic site which is why it doesn't really need SQL Express. I could just hard code the map in but I was hoping to use the site as an example for clients. An interactive map control is always a nice thing to show off in the CMS.  I guess I'll transfer over to SQL Express. If Stephan's had problems with localDB I'll have no chance. I just want to build a site not fix databases ;)

Thanks again.

**Comment by craigs100** [comment]
Confirmed, switching to SQL Express fixed it !
