### ISSUE TITLE
Add partial to App_Plugins folder

### ISSUE THREAD

**Issue by bjarnef** [ArnoldV/Our.Umbraco.GMaps#32]
It seems the package installs a default/sample partial views directly in `~/Views/Partials/` folder.

I think it would be better to include this in `App_Plugins` folder like we do in Vendr Reviews:
https://github.com/vendrcontrib/vendr-reviews/blob/dev/src/Vendr.Contrib.Reviews/Web/UI/App_Plugins/VendrReviews/Views/Partials/VendrReviews.cshtml

It could have an extension method to render this with a few configuration options.

For more a more advanced/complex map the developer can render the map from a custom partial using the `GmapsModel`.

**Comment by ronaldbarendse** [comment]
Packages shouldn't put files into the projects Views folder indeed 😉 But even Umbraco (Grid and Block list) and Umbraco Forms still do this, making customizing these files very error prone, as updates might overwrite the customizations. Automatic patches on Umbraco Cloud makes this even more problematic...

That's also part of the reason why version 2 of this package will remove this view and extension method! The other reason being that it didn't support rendering multiple maps on a page (as it used HTML IDs and included the Google Maps JavaScript API on every call).
