### ISSUE TITLE
GMaps.Core dependency

### ISSUE THREAD

**Issue by bjarnef** [ArnoldV/Our.Umbraco.GMaps#33]
I noticed there are the following two packages on NuGet:
https://www.nuget.org/packages/Our.Umbraco.GMaps/
https://www.nuget.org/packages/Our.Umbraco.GMaps.Core/

I would expect the Our.Umbraco.GMaps had a dependency listed on Our.Umbraco.GMaps.Core, but it doesn't.

Furthermore the latest version is v1.3.3, but there is only a single version v1.2.1 of Our.Umbraco.GMaps.Core

Is Our.Umbraco.GMaps.Core NuGet package still used? and why doesn't the version number match like in e.g. Umbraco and Umbraco Forms where tehy have the `*.Core` dependency?

**Comment by ronaldbarendse** [comment]
Version 2 of this package will support seperate NuGet packages: https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/8.

I didn't know @ArnoldV already created a version for [Our.Umbraco.GMaps.Core](https://www.nuget.org/packages/Our.Umbraco.GMaps.Core/1.2.1); maybe that can be delisted to avoid confusion? At least the NuGet name is already reserved now 😉

**Comment by bjarnef** [comment]
Okay, so for now I would have to reference Our.Umbraco.GMaps.dll in the "Web" project from a core/library project?

Currently I have the following

```
string json = @"{
  'address': {
    'latlng': '',
    'full_address': '',
    'postalcode': '',
    'city': '',
    'state': '',
    'country': ''
  }
}";

JObject mapObject = JObject.Parse(json);
JObject address = (JObject)mapObject["address"];

address["latlng"] = $"{googleAddress.Coordinates.Latitude.ToString(CultureInfo.InvariantCulture)}, {googleAddress.Coordinates.Longitude.ToString(CultureInfo.InvariantCulture)}";
address["full_address"] = googleAddress.FormattedAddress;

address["postalcode"] = store.Zip;
address["city"] = store.City;
address["country"] = store.CountryName;

node.SetValue("location", mapObject.ToString());
```

but I can probably assign values to an instance of `GmapsModel` instead an serialize this.
