### ISSUE TITLE
Map style is null

### ISSUE THREAD

**Issue by Slipoch** [ArnoldV/Our.Umbraco.GMaps#39]
Map style always seems to come out null, throwing an error here in MapScripts.cshtml: 
` var stylesObject = Html.Raw(JsonConvert.DeserializeObject(Model.MapConfig.Style));`
Recommend changing to 
`var stylesObject = Html.Raw(JsonConvert.DeserializeObject(Model.MapConfig.Style ?? ""));`

**Comment by ronaldbarendse** [comment]
The `MapScripts.schtml` won't be included in new versions, but your recommendation can indeed be manually applied to existing projects using it. Thanks for providing the feedback and work-around 👍🏻
