### ISSUE TITLE
GMaps issues with blocklist editor

### ISSUE THREAD

**Issue by Slipoch** [ArnoldV/Our.Umbraco.GMaps#40]
When adding maps into a block, the autocomplete modal is invisible (placed offscreen and no height, low z-index) 

Related to #23 

Suggest hooking the autocomplete onto x/y or area of a div under the textfield

**Comment by ronaldbarendse** [comment]
This is the same issue as https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/22 and as I've commented, can't be easily fixed, because the Google Maps Place Autocomplete widget adds it's container at the end of the document...
