### ISSUE TITLE
How to reset field value

### ISSUE THREAD

**Issue by enriquin** [ArnoldV/Our.Umbraco.GMaps#43]
Hello!
We have came accross one little problem:

Once you set a value for the map, it seems imposible to reset the value of the field (to null): It seems that even if you delete the value for the textfield, the control gets it again from the map marker coordinates.

A "reset value" button would be very useful!

**Comment by ronaldbarendse** [comment]
Having a way to reset the values makes sense indeed! We can implement this using a [property action](https://our.umbraco.com/documentation/extending/property-editors/Property-Actions/) 👍🏻

**Comment by robertjf** [comment]
This is now resolved in version 2.0.1
