### ISSUE TITLE
Smidge cannot minify JS files in production

### ISSUE THREAD

**Issue by rickbutterfield** [ArnoldV/Our.Umbraco.GMaps#69]
When deployed to a production site (with `Umbraco:CMS:Hosting:Debug: true` and `ASPNETCORE_ENVIRONMENT` set to `Production`) the `maps.controller.js` file causes Smidge to error and not minify the file due to this error:

```
System.InvalidOperationException: /App_Plugins/Our.Umbraco.GMaps/js/maps.controller.js(105,5-11): run-time error JS1292: Strict-mode does not allow duplicate property names: street
```

I believe removing the duplicate `street` entry in `getAddressObject()` should fix this

**Comment by robertjf** [comment]
Thanks @rickbutterfield - good catch.

**Comment by robertjf** [comment]
@rickbutterfield there's a new 2.0.3-pre001 release available on NuGet for you to test... let us know if you experience any issues...

**Comment by rickbutterfield** [comment]
@robertjf It's worked a treat! Thank you
