### ISSUE TITLE
Unable to set the value to Null

### ISSUE THREAD

**Issue by Myster** [ArnoldV/Our.Umbraco.GMaps#90]
Hi,
Sometimes I property should have no value (null)
I don't see that this is possible with a property using the GMaps property editor.

**Comment by robertjf** [comment]
@Myster if you're using the current version, there's a [Property Action](https://our.umbraco.com/documentation/Extending/Property-Editors/Property-Actions/) on the Maps Datatype that allows you to clear the value.

**Comment by Myster** [comment]
Oh wow, you learn something new every day. Thanks.
