### ISSUE TITLE
MapConfig.CenterCoordinates is NULL

### ISSUE THREAD

**Issue by benehudson** [ArnoldV/Our.Umbraco.GMaps#92]
I'm assuming MapConfig.CenterCoordinates should return the Default Coordinates set on the config screen, right?  I've got coordinates set, and it's returning null.  I'm able to pull the APIkey and the Zoom from MapConfig.  But, I'm lost as to why the CenterCoordinates are coming back null. PS: this is v 2.05

**Comment by benehudson** [comment]
I rolled back to v1.3.3 and that solved the issue for me.

**Comment by robertjf** [comment]
@benehudson this sounds like a legacy data issue - the upcoming 2.0.6 release should resolve this.
